[package]
name = "havel_hakimi"
version = "0.1.0"
authors = ["Nils Rauch <nils.rauch@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
